import { Form } from "react-router-dom";

export { default as Main } from "./Main";
export { default as Navbar } from "./Navbar";
export { default as Home } from "./Home";
export { default as listData } from "./listData";
export { default as ChooseCategories } from "./ChooseCategories";
export { default as FinalRec } from  "./FinalRec";
export { default as LoadingRec } from "./LoadingRec";
export { default as Fantasy } from "./Fantasy";
// export { default as Fiction } from "./Fiction";
// export { default as GraphicNovel } from "./GraphicNovel";
export { default as Mystery } from "./Mystery";
export { default as Nonfiction } from "./Nonfiction";
export { default as Romance } from "./Romance";
export { default as SciFi } from "./SciFi";
// export { default as YAFiction } from "./YAFiction";
export { default as FantasyTest } from "./FantasyTest";
export { default as Contact } from "./Contact"; 
export { default as finalTest } from "./finalTest";